import type { NextPage } from "next";
import Head from "next/head";
import { VStack, Text } from "@chakra-ui/react";
import { getEvents } from "../services/apiService";
import { dehydrate, QueryClient, useQuery } from "react-query";

const Home: NextPage = () => {
  const { data: events, isLoading } = useQuery("users", getEvents);

  if (isLoading || !events) return null;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        {events.map((event) => (
          <Text key={event.id}>{event.name}</Text>
        ))}
      </VStack>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery("posts", getEvents);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
